### PR TITLE
Fix DEPRECATION WARNING: to_prepare is deprecated and will be removed…

### PR DESCRIPTION
**Pull request by Fudoshiki**
… from Rails 5.2

### CODE REVIEW

**Comment by chamnap** [comment]
+1

**Comment by Fudoshiki** [comment]
@chamnap need changes for merge?

**Comment by Fudoshiki** [comment]
@chamnap need your attention

**Comment by chamnap** [comment]
This gem doesn't support rails 5 yet.

**Comment by Fudoshiki** [comment]
I have rails 5 and mongoid 6, gem works fine without any issues

**Comment by chamnap** [comment]
@Fudoshiki, we should do an `if/else` to support rails 4 as well. Something like this:

```
if defined? ActiveSupport::Reloader
  ActiveSupport::Reloader.to_prepare(...)
else
  ActionDispatch::Reloader.to_prepare(...)
end
```

**Pull request merged**
